# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acd86eb063c79be0f8c72ddfe42c3144fc0df93a27d3a26719d15b34ba684023524e14d71b83b1928e79b60531dd34f0d0908c781e92e9a25354868b7341c4cf

test:
  secret_key_base: 5325b4003b6d76007b8f9af3bb5dc8ae6403995172f28b6dc84d1f42f146741b35d51471dff475c28cda4efb6b73cd0a57268a976c4d370cba7681da0c16a410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
